version: '3'
services:
  emqx:
    image: emqx/emqx:5.8.6
    user: root
    container_name: emqx
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    networks:
      emqx-bridge:
        aliases:
          - broker.emqx.io
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
      - "14567:14567/udp"
    environment:
      - EMQX_LISTENERS__QUIC__DEFAULT__keyfile=/tmp/server.key
      - EMQX_LISTENERS__QUIC__DEFAULT__certfile=/tmp/server.pem
      - EMQX_LISTENERS__QUIC__DEFAULT__ENABLED=true
    volumes:
      - ./emqx_confs:/opt/emqx/data/configs
      - ./certs/emqx:/opt/emqx/data/certs
      - ./certs/client:/tmp/


networks:
  emqx-bridge:
    driver: bridge
