sequenceDiagram
    EMQX->>Cliente: QUIC Packet 0 (Entregue)
    Cliente-->>EMQX: QUIC Packet 1 (Entregue)
    Cliente-->>EMQX: QUIC Packet 2 (Entregue)
    Cliente-->>EMQX: QUIC Packet 3 (Entregue)
    EMQX--xCliente: QUIC Packet 4 (Perdido)
    Cliente-->>EMQX: QUIC Packet 5 (Entregue)
    EMQX--xCliente: QUIC Packet 6 (Perdido)
    Cliente-->>EMQX: QUIC Packet 7 (Entregue)
    EMQX->>Cliente: QUIC Packet 8 (Entregue)
    EMQX->>Cliente: QUIC Packet 9 (Entregue)
    EMQX->>Cliente: QUIC Packet 10 (Entregue)
    EMQX->>Cliente: QUIC Packet 11 (Entregue)
    EMQX->>Cliente: QUIC Packet 12 (Entregue)
    EMQX->>Cliente: QUIC Packet 13 (Entregue)
    EMQX->>Cliente: QUIC Packet 14 (Entregue)
    EMQX->>Cliente: QUIC Packet 15 (Entregue)
    EMQX->>Cliente: QUIC Packet 16 (Entregue)
    EMQX->>Cliente: QUIC Packet 17 (Entregue)
    EMQX->>Cliente: QUIC Packet 18 (Entregue)
    EMQX->>Cliente: QUIC Packet 19 (Entregue)
    EMQX->>Cliente: QUIC Packet 20 (Entregue)
    EMQX->>Cliente: QUIC Packet 21 (Entregue)
    EMQX->>Cliente: QUIC Packet 22 (Entregue)
    EMQX->>Cliente: QUIC Packet 23 (Entregue)
    EMQX->>Cliente: QUIC Packet 24 (Entregue)
    EMQX->>Cliente: QUIC Packet 25 (Entregue)
    EMQX->>Cliente: QUIC Packet 26 (Entregue)
    EMQX->>Cliente: QUIC Packet 27 (Entregue)
    EMQX->>Cliente: QUIC Packet 28 (Entregue)
    EMQX->>Cliente: QUIC Packet 29 (Entregue)
    EMQX->>Cliente: QUIC Packet 30 (Entregue)
    EMQX->>Cliente: QUIC Packet 31 (Entregue)
    EMQX->>Cliente: QUIC Packet 32 (Entregue)
    EMQX->>Cliente: QUIC Packet 33 (Entregue)
    EMQX->>Cliente: QUIC Packet 34 (Entregue)
    EMQX->>Cliente: QUIC Packet 35 (Entregue)
    EMQX->>Cliente: QUIC Packet 36 (Entregue)
    EMQX->>Cliente: QUIC Packet 37 (Entregue)
    EMQX->>Cliente: QUIC Packet 38 (Entregue)
    EMQX->>Cliente: QUIC Packet 39 (Entregue)
    EMQX->>Cliente: QUIC Packet 40 (Entregue)
    EMQX->>Cliente: QUIC Packet 41 (Entregue)
    EMQX->>Cliente: QUIC Packet 42 (Entregue)
    EMQX->>Cliente: QUIC Packet 43 (Entregue)
    EMQX->>Cliente: QUIC Packet 44 (Entregue)
    EMQX->>Cliente: QUIC Packet 45 (Entregue)
    EMQX->>Cliente: QUIC Packet 46 (Entregue)
    EMQX->>Cliente: QUIC Packet 47 (Entregue)
    EMQX->>Cliente: QUIC Packet 48 (Entregue)
    EMQX->>Cliente: QUIC Packet 49 (Entregue)
    EMQX->>Cliente: QUIC Packet 50 (Entregue)
    EMQX->>Cliente: QUIC Packet 51 (Entregue)
    EMQX--xCliente: QUIC Packet 52 (Perdido)
    EMQX--xCliente: QUIC Packet 53 (Perdido)
    EMQX--xCliente: QUIC Packet 54 (Perdido)
    EMQX--xCliente: QUIC Packet 55 (Perdido)
    EMQX--xCliente: QUIC Packet 56 (Perdido)
    EMQX--xCliente: QUIC Packet 57 (Perdido)